# Generated by Django 4.1 on 2023-04-08 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_alter_product_image1_alter_product_image2_and_more'),
        ('shoppingcart', '0002_alter_shoppingcart_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productincart', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины',
            },
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
        migrations.AddConstraint(
            model_name='productinshoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_product_in_shoppingcart'),
        ),
    ]
