# Generated by Django 4.1 on 2023-04-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0003_productinshoppingcart_delete_shoppingcart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='shoppingcart.productinshoppingcart', verbose_name='Товар')),
            ],
        ),
    ]
