# Generated by Django 4.1 on 2023-04-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0004_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='total_sum',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
