# Generated by Django 4.1 on 2023-04-08 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0005_shoppingcart_total_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='products',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.productinshoppingcart', verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
