# Generated by Django 4.1 on 2023-04-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0010_remove_shoppingcart_user_productinshoppingcart_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='products',
        ),
        migrations.DeleteModel(
            name='ProductInShoppingCart',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
