# Generated by Django 4.1 on 2023-04-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0012_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productinshoppingcart',
            constraint=models.UniqueConstraint(fields=('product', 'cart'), name='unique_product_in_cart'),
        ),
    ]
