# Generated by Django 4.1 on 2023-04-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0013_productinshoppingcart_unique_product_in_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'корзина', 'verbose_name_plural': 'корзины'},
        ),
    ]
