# Generated by Django 4.1 on 2023-04-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageInProduct',
        ),
    ]
